title: Michael Byrne's Blog
author: Michael Byrne

description: >- 
  Consultant specialising in behaviour simulation and data visualisation. 
  Currently building city-scale travel forecasting tools at Arup.

baseurl: ""
url: "https://michaelbyrne.au"
domain: michaelbyrne.au

email: michael@michaelbyrne.au
github_username:  MichaelByrneAU
linkedin_username: MichaelByrneAU

theme: minima
minima:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
