base_url = "https://michaelbyrne.au"
title = "Michael Byrne"
description = "Software engineering and data visualisation"
author = "Michael Byrne"

compile_sass = true
build_search_index = false
generate_feed = true

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "OneHalfLight"
smart_punctuation = true

[extra]
email = "michael@michaelbyrne.au"
links = [{ name = "Home", url = "/" }, { name = "About", url = "/about" }]
socials = [
  { name = "GitHub", url = "https://github.com/MichaelByrneAU" },
  { name = "LinkedIn", url = "https://www.linkedin.com/in/michaelbyrneau/" },
]
